### ISSUE TITLE
Day-Specific Hourly Goals

### ISSUE THREAD

**Issue by blachniet** [blachniet/timetonight#4]
Goals for each day. For example:

``` toml
[HoursPerDay]
Sunday = 0
Monday = 9
Tuesday = 9
Wednesday = 9
Thursday = 10
Friday = 8
Saturday = 10
```
